"""The task board: one home for every piece of work, generated to CSV.

WHY A MODULE AND NOT A CSV HAND-EDITED
--------------------------------------
`docs/TASKS.csv` is GENERATED by `uv run xat-practice tasks`, from the records
below, and a staleness test compares the two.

The alternative -- editing the CSV by hand -- creates the defect this project keeps
paying for: two places to change. `todo.txt` and the CSV would drift, and the
narrative would silently contradict the board. So the records live here, the CSV is
a view of them, and `todo.txt` points at them.

The columns are Jira's, because a board is a board whatever it is called:
`id`, `type`, `epic`, `priority`, `status`, `owner`, `evidence`, `why`,
`acceptance`, `falsifying_input`, `blocks`, `source`.

TWO OF THOSE COLUMNS ARE THE POINT
----------------------------------
`owner` is an `opencode.json` role, and `evidence` is what that role is allowed to
look at. MEASURED 2026-10-02: the project scopes its ten agents in prose in
AGENTS.md, and nothing tied a task to a role -- so nothing stopped the right
question being asked of the wrong reviewer.

`falsifying_input` is the WRONG input a check must fail on. A task with no
falsifying input is a task that can be declared done by a test that has only ever
seen a true statement, which is how `test_the_reveal_button_starts_disabled` once
asserted that an *enabling* line existed while the button was never disabled.
"""

from __future__ import annotations

import csv
import io
from dataclasses import dataclass, field
from datetime import date

COLUMNS = (
    "id", "type", "epic", "priority", "status", "owner", "evidence",
    "title", "why", "acceptance", "falsifying_input", "blocked_by", "source",
)

RECORDED = "2026-10-02"


@dataclass(frozen=True, slots=True)
class Task:
    id: str
    type: str
    epic: str
    priority: str
    status: str
    owner: str
    evidence: str
    title: str
    why: str
    acceptance: str
    falsifying_input: str
    blocked_by: str = ""
    source: str = ""
    notes: str = field(default="", repr=False)

    def row(self) -> dict[str, str]:
        return {c: str(getattr(self, c)) for c in COLUMNS}


#: Priority meanings, so "P0" is not a mood.
PRIORITY_LEGEND = {
    "P0": "correctness -- wrong output teaches a wrong fact",
    "P1": "the next thing to build; blocks other work",
    "P2": "honesty of what the product reports",
    "P3": "housekeeping; nothing is wrong without it",
}

STATUS_LEGEND = {
    "TODO": "not started",
    "DONE": "landed, with its falsifying input shown",
    "REJECTED": "decided against; the reason is the point",
    "BLOCKED": "cannot start until `blocks` clears",
}


TASKS: tuple[Task, ...] = (
    # ---------------------------------------------------------------- EXAM LAYER
    Task(
        id="TASK-001", type="bug", epic="EXAM-LAYER", priority="P0", status="DONE",
        owner="code-reviewer", evidence="the source and `git diff`",
        title="Blank penalty was on SectionSpec, implying 8 free blanks per section",
        why=("XAT's rule is '-0.10 for every unattempted question after the first "
             "eight', and Part 1 is ONE pool of 75 questions. Eight free blanks in "
             "total is the truth; eight per section told a learner they could skip "
             "24 and lose ~1.6 marks. A wrong default here is a false ATTEMPT "
             "STRATEGY, and strategy is the product."),
        acceptance=("PartSpec owns blank_penalty, blank_penalty_after, minutes and "
                    "in_percentile; SectionSpec keeps options and per-answer marking."),
        falsifying_input=("test_the_blank_penalty_counts_across_the_part_not_within"
                          "_a_section: 4+3+3 blanks = -0.20 while no section exceeds "
                          "8"),
        source="Claude.ai + Perplexity.ai, independently",
    ),
    Task(
        id="TASK-002", type="bug", epic="EXAM-LAYER", priority="P0", status="DONE",
        owner="code-reviewer", evidence="the source",
        title="SectionSpec.stratum was a single value, and it was wrong",
        why="QA&DI holds 37 QUANT and 3 LOGIC subtopics. A single Stratum is a lie.",
        acceptance="strata() derives the distribution; no single-value field remains.",
        falsifying_input="test_a_section_is_a_mix_of_strata_not_one_value (37 and 3)",
        source="Perplexity.ai",
    ),
    Task(
        id="TASK-003", type="decision", epic="EXAM-LAYER", priority="P0",
        status="REJECTED", owner="mentor", evidence="the syllabus and the code",
        title="Keep the '>=10 named traps' figure as a GATE",
        why=("Claude.ai proposed replacing it with a coverage matrix (8-10 traps, 5 "
             "templates, 4 foundation, 6 medium, 4 hard, 2 transfer). Those numbers "
             "are unmeasured, and making an invented threshold a gate is D13's "
             "error. A subtopic with ten near-duplicate labels would pass."),
        acceptance=("trap count stays a READINESS indicator in the coverage ledger, "
                    "not a gate. The authoring/drill/mock-readiness vocabulary is "
                    "adopted."),
        falsifying_input="n/a -- a rejection",
        source="Claude.ai + Perplexity.ai, agreed",
    ),
    Task(
        id="TASK-004", type="decision", epic="EXAM-LAYER", priority="P1",
        status="BLOCKED", owner="mentor", evidence="the syllabus table",
        title="Adopt per-level target times of 30-75s .. 150-300s",
        why=("Claude.ai's table CONFLICTS with our own G9, which refuses any item "
             "over 2 minutes. The Hard band of 150-300s would be refused by our own "
             "gate. Adopting it silently would either break G9 or raise it without "
             "evidence."),
        acceptance=("reconcile with G9 first. Do NOT silently raise G9. A stated "
                    "budget per level, or none."),
        falsifying_input="write a 240s hard item and confirm G9 refuses it",
        blocked_by="TASK-020",   # a time budget only means something against a mock
        source="Claude.ai",
    ),
    Task(
        id="TASK-005", type="task", epic="EXAM-LAYER", priority="P1", status="TODO",
        owner="code-reviewer", evidence="the source",
        title="Three homes for the same marking: gates.py, expected_ev, SectionSpec",
        why=("gates.py computes G15's score from literals +1/-0.25; "
             "items.expected_ev has its own defaults; SectionSpec declares them. "
             "When CAT lands, G15's ceiling stays calibrated to XAT marking with "
             "nothing to say so."),
        acceptance=("gates read marking from SectionShape; QUANT_MOCK and FULL_MOCK "
                    "derive from SECTIONS/EXAMS instead of repeating 28, 170, 5."),
        falsifying_input=("change the marking in SECTIONS and show G15's refusal "
                          "count does NOT move -- that is the leak"),
        source="code-reviewer + ADOPT_REJECT 4.11",
    ),
    Task(
        id="TASK-006", type="task", epic="EXAM-LAYER", priority="P2", status="TODO",
        owner="code-reviewer", evidence="the source",
        title="Item.options override and effective_options(item, section)",
        why=("CAT mixes MCQ and non-MCQ in one section. EV must read the ITEM's "
             "effective options, not the section default."),
        acceptance="Item carries an override; effective_options() is what gates use.",
        falsifying_input="an item with options=4 in a 5-option section",
        source="Claude.ai",
    ),
    Task(
        id="TASK-007", type="task", epic="EXAM-LAYER", priority="P2", status="TODO",
        owner="mentor", evidence="the code and the data model",
        title="Edition is 2026 but the paper being sat is most likely 2027",
        why=("It is October 2026. `edition=\"2026\"` silently asserts next year has "
             "identical counts, marking, blank rule and calculator policy."),
        acceptance=("verified_against and evidence are asserted; full per-edition "
                    "keying deferred until a second edition exists."),
        falsifying_input="rename the edition and confirm nothing claims it is 2027",
        source="Perplexity.ai",
    ),

    # ------------------------------------------------------------- LESSON LOOP
    Task(
        id="TASK-010", type="story", epic="LESSON-LOOP", priority="P1",
        status="TODO", owner="viewer", evidence="a rendered paper, sat as a learner",
        title="Per-level choice: finish / next level / MORE AT THIS LEVEL",
        why=("The owner's complaint: the ladder is a mandatory queue FOUNDATION->EASY"
             "->MEDIUM->HARD with a single Finish at the end. There is no way to say "
             "'give me four more at foundation' -- which is the request a learner "
             "actually makes when a rung felt easy. D26 already says the level is the "
             "learner's; the UI does not offer it."),
        acceptance=("after each rung the page offers three routes: finish the lesson, "
                    "take the next rung, or request N more items AT THIS RUNG. More "
                    "requires a level-filtered block to exist (TASK-014)."),
        falsifying_input=("pick a rung, choose 'more', and confirm the new items are "
                          "the SAME level -- not a reshuffle of the four"),
        # MEASURED 2026-10-02: I wrote this as `blocks=TASK-014`, which reads as "010
        # blocks 014" and created a 010 <-> 014 cycle. The direction is the other
        # way: offering 'more' REQUIRES blocks to exist, and the column is
        # `blocked_by`. Both inversions were found by test_a_circular_block_chain.
        blocked_by="TASK-014",
        source="owner, 2026-10-02",
    ),
    Task(
        id="TASK-011", type="story", epic="LESSON-LOOP", priority="P1",
        status="TODO", owner="viewer", evidence="a rendered finish screen",
        title="The finish screen is not diagnostic -- it repeats one verdict",
        why=("MEASURED output: FOUNDATION wrong, EASY wrong, MEDIUM wrong, HARD wrong "
             "produced three identical lines, 'Unsure and wrong - normal, and the "
             "cheapest kind of miss', and one 'Sure and WRONG'. With four items that "
             "is noise, and it names no next action. It is a per-item log dressed as "
             "a diagnosis."),
        acceptance=("the screen states which cell mattered, what it means, and ONE "
                    "concrete next action, derived from the actual log -- not a "
                    "template sentence repeated per rung."),
        falsifying_input=("answer all four identically and confirm the screen still "
                          "produces a DIFFERENT, specific next action per outcome"),
        source="owner, 2026-10-02",
    ),
    Task(
        id="TASK-012", type="bug", epic="LESSON-LOOP", priority="P1", status="TODO",
        owner="level-auditor", evidence="derive_level output vs the claimed tier",
        title="Four items, one per level, cannot separate 'unsure and wrong' from noise",
        why=("One item per rung means the per-rung verdict has n=1. 'Unsure and "
             "wrong' three times may be three misunderstandings or one bad afternoon; "
             "the screen cannot tell, and neither can we. This is a MEASUREMENT "
             "limit, not a wording problem."),
        acceptance=("either more items per level, or the screen stops claiming to "
                    "diagnose from one observation and says what it can support"),
        falsifying_input=("show two identical answer patterns producing different "
                          "screens -- if they cannot differ, n=1 is the ceiling"),
        source="owner + AGENTS.md D6",
    ),
    Task(
        id="TASK-013", type="decision", epic="LESSON-LOOP", priority="P1",
        status="TODO", owner="mentor", evidence="the syllabus table and the ledger",
        title="Prerequisite graph, so 'next lesson' means REACHABLE not BIGGEST",
        why=("DI is the biggest block (6.71 q/yr) and is not reachable: avg_ratio has "
             "0 of 3 subtopics written and pct is 0.0 UNMEASURED. Writing DI first "
             "teaches shortcuts to a learner with no foundations."),
        acceptance=("PREREQUISITES is data; self_check refuses a cycle; the ledger "
                    "or a verb prints the highest-weight reachable node."),
        falsifying_input="add a cycle to PREREQUISITES and confirm the build refuses",
        source="Perplexity.ai -- REVERSED my own earlier recommendation",
    ),
    Task(
        id="TASK-014", type="task", epic="LESSON-LOOP", priority="P1",
        status="BLOCKED", owner="mentor", evidence="the coverage ledger",
        title="20-item LEVEL-FILTERED blocks",
        why=("What 'more at this level' actually draws from. G11 must NEVER be handed "
             "a single-level drill: it would refuse items for 'under quota (0/5)', "
             "the D12 defect that deleted Lesson 1's hard rung."),
        acceptance="a block builds and is servable; G11 does not run on it.",
        falsifying_input=("run the drill through G11 and watch it refuse valid items "
                          "-- that is the defect, not a pass"),
        blocked_by="TASK-015",   # blocks need traps before they can exist
        source="D26",
    ),
    Task(
        id="TASK-015", type="task", epic="LESSON-LOOP", priority="P1", status="TODO",
        owner="question-setter", evidence="paper vs docs/PEDAGOGY.md",
        title="Fold authored misconceptions into Subtopic.traps",
        why=("block capacity reads 0 of 40, so NO 20-item block can exist. Lesson 1 "
             "has 20 traps; Lesson 2 has 3 syllabus traps against 16 item-level "
             "misconceptions. The misconceptions exist -- they are just not in the "
             "syllabus. Move real authored text; invent nothing."),
        acceptance=("coverage shows block capacity > 0 and every added trap is "
                    "traceable to an authored distractor"),
        falsifying_input=("count the traps before and after writing one lesson and "
                          "confirm the delta equals its distinct authored "
                          "misconceptions"),
        source="blocker for TASK-014",
    ),
    Task(
        id="TASK-016", type="task", epic="LESSON-LOOP", priority="P1",
        status="TODO", owner="code-reviewer", evidence="the source",
        title="Item.Set for shared stimuli",
        why=("XAT DI and caselet items arrive as 3-5 questions over ONE stimulus. "
             "G11's mix and the one-rung-per-level check both assume one item, one "
             "key, one rung. Also the strongest use of D1: DI data generated "
             "parametrically and solved by exact arithmetic."),
        acceptance="a set builds and passes every gate; G17 compares shapes within a set.",
        falsifying_input=("a two-item set where G11 or the rung check raises -- that "
                          "is the breakage, not a pass"),
        # Not blocked: `Item.Set` is new work with no prerequisite. The old
        # `blocks=TASK-017` inverted it and made 016 <-> 017 a cycle.
        source="Perplexity.ai",
    ),
    Task(
        id="TASK-017", type="task", epic="LESSON-LOOP", priority="P1",
        status="BLOCKED", owner="question-setter", evidence="the syllabus",
        title="Data Interpretation content",
        why=("The largest block and the biggest hole: 6.71 q/yr, 24% of the section, "
             "zero lessons. Reachable only after TASK-013 and TASK-016."),
        acceptance="4 rungs, keys re-derived, 4/4 shapes, step-by-step that teaches.",
        falsifying_input="plant a wrong key and confirm G5 REFUSES it",
        blocked_by="TASK-016, TASK-013",
        source="measured weight",
    ),
    Task(
        id="TASK-018", type="task", epic="LESSON-LOOP", priority="P2",
        status="TODO", owner="code-reviewer", evidence="the source",
        title="Distractor.trap_id",
        why=("Subtopic.traps and distractor.misconception are parallel lists with "
             "nothing joining them. G16 proves the arithmetic; nothing proves the "
             "distractor draws from the declared trap set. This is what makes a "
             "learner response log analysable."),
        acceptance="every distractor names a trap that exists on its subtopic.",
        falsifying_input=("point a distractor at a nonexistent trap_id and confirm a "
                          "gate refuses it"),
        source="Claude.ai + Perplexity.ai",
    ),
    Task(
        id="TASK-019", type="task", epic="LESSON-LOOP", priority="P2",
        status="TODO", owner="viewer", evidence="the browser",
        title="Learner response logging (time, chosen option, which trap)",
        why=("derive_level is calibrated against our own guess about difficulty. "
             "There is no learner data at all. Store locally, exportable."),
        acceptance="a run produces a log a learner can export and read back.",
        falsifying_input=("clear storage, reload, and confirm the log is EMPTY -- a "
                          "check that cannot fail has not been tested"),
        source="Perplexity.ai",
    ),
    Task(
        id="TASK-020", type="task", epic="LESSON-LOOP", priority="P2",
        status="TODO", owner="paper-auditor", evidence="a paper vs the XAT spec",
        title="MOCK-QA 28 then MOCK-FULL 75",
        why=("Directionally right, but a mock is not an item count: it needs a topic "
             "cap and no duplicate method templates, and its level mix before "
             "learner data exists is UNMEASURED and must be labelled so."),
        acceptance=("a mock builds, closes, respects a topic cap, and reports its mix "
                    "with a basis"),
        falsifying_input="a mock with 10 questions from one narrow subtopic must refuse",
        source="LLD Phase D",
    ),

    # -------------------------------------------------------------- TEST INFRA
    Task(
        id="TASK-030", type="bug", epic="TEST-INFRA", priority="P0", status="DONE",
        owner="tester", evidence="the gate suite and a real generated paper",
        title="ui_probe.html audited a hand-copied shell",
        why=("It carried its own <main>, its own <h1>Lesson 1 - Simple Interest</h1> "
             "and only borrowed lesson.js -- so it audited a DUPLICATE of the markup. "
             "It had already drifted: the heading still said Simple Interest on the "
             "GEOMETRY lesson, and it had no back link, which is why no check noticed "
             "the back link was broken."),
        acceptance="the probe starts from the served index.html and injects only itself.",
        falsifying_input="break a piece of static markup and confirm a check fails",
        source="TASK-031",
    ),
    Task(
        id="TASK-031", type="bug", epic="TEST-INFRA", priority="P0", status="DONE",
        owner="ui-inspector", evidence="the rendered DOM plus the pixels",
        title="Back link served a directory listing with HTTP 200",
        why=("It was href='../', correct at out/<lesson>/. The exam layer nested the "
             "output, so ../ resolved to a directory with no index.html -- and "
             "SimpleHTTPRequestHandler answers that with a DIRECTORY LISTING. 200, so "
             "nothing went red, and the learner got a raw file index."),
        acceptance="depth computed at build time; two checks pin it.",
        falsifying_input="restore the old '../' and confirm the test fails",
        source="owner report, 2026-10-02",
    ),
    Task(
        id="TASK-032", type="task", epic="TEST-INFRA", priority="P1", status="TODO",
        owner="tester", evidence="the gate suite plus a real browser",
        title="UI COVERAGE MAP: name every control the probe never touches",
        why=("MEASURED 2026-10-02. The probe makes 56 checks and drives ONE path. It "
             "clicks #reveal, [data-conf=sure], #check, ONE option, #next and the HARD "
             "tab. It NEVER touches: #freeAnswer (0 mentions -- the textarea where the "
             "learner writes their working), #startQ (0 mentions -- the teach-card "
             "dismiss), the `unsure` button, or the other 4 of 5 options. No keyboard "
             "test at all. So the harness exists and the COVERAGE does not."),
        acceptance=("every control in the page appears in the probe or in a written "
                    "exemption with a reason; the map is checked in, not derived from "
                    "memory"),
        falsifying_input=("add a control to the page and confirm the map test fails "
                          "until it is covered or exempted"),
        source="measured 2026-10-02",
    ),
    Task(
        id="TASK-033", type="task", epic="TEST-INFRA", priority="P1", status="TODO",
        owner="tester", evidence="the gate suite plus a real browser",
        title="Scenario files instead of one inline driver",
        why=("The probe is one 600-line injected script, so scenarios cannot be run "
             "independently, skipped, or read individually -- which is why three "
             "attempts to add the finish-screen check fought each other over timing."),
        acceptance=("each scenario is its own named file; running one alone works; a "
                    "failure names the scenario"),
        falsifying_input=("run a single scenario by name and confirm it exercises only "
                          "that scenario"),
        source="measured: three attempts to add one check fought over waitFor timing",
    ),
    Task(
        id="TASK-034", type="task", epic="TEST-INFRA", priority="P2", status="TODO",
        owner="tester", evidence="the gate suite",
        title="Keyboard path for the level tabs and the reveal button",
        why=("The tabs are <button>s and were made focusable deliberately, and "
             "nothing tests Enter or Space on them. An element that is focusable but "
             "unusable by keyboard is broken for a real user and green in CI."),
        acceptance="Enter and Space on a rung tab move the level; asserted.",
        falsifying_input=("focus a tab and press Enter; a page that ignores it must "
                          "fail"),
        source="TASK-010 makes tabs a primary control",
    ),
    Task(
        id="TASK-035", type="task", epic="TEST-INFRA", priority="P1", status="TODO",
        owner="tester", evidence="the four gate commands over a named population",
        title="Refusal counts per gate, per lesson, per run",
        why=("A gate that refuses nothing across every run is indistinguishable from "
             "a gate that is unreachable, and this project has shipped one. We report "
             "admitted/refused totals but never the per-gate histogram over time."),
        acceptance="the verb prints per-gate counts; a gate that never fires is named.",
        falsifying_input="disable a gate and confirm the histogram reports the drop",
        source="AGENTS.md tester role",
    ),

    # ------------------------------------------------------------- DOCUMENTATION
    Task(
        id="TASK-040", type="decision", epic="DOCUMENTATION", priority="P2",
        status="REJECTED", owner="mentor", evidence="prose against the files",
        title="Promote the ad-hoc '28.00' area sum into an enforced invariant",
        why=("It was an ad-hoc shell calculation with no command, no test and no "
             "function. Promoting it into a gate is MEASURED silently becoming "
             "ASSUMPTION, and the grouping is a SECONDARY SOURCE (D13)."),
        acceptance=("demoted to prose marked not-re-derivable; the display layer is "
                    "added only if the owner asks for the external grouping"),
        falsifying_input="n/a -- a rejection",
        source="doc-reviewer",
    ),
    Task(
        id="TASK-041", type="task", epic="DOCUMENTATION", priority="P3",
        status="TODO", owner="doc-reviewer", evidence="prose against the files",
        title="Counts quoted in prose drift; the build does not notice",
        why=("README and DECISIONS said '90 named traps' while the code said 104. "
             "A number written into a sentence has no owner and no staleness test."),
        acceptance=("prose references the generated ledger rather than restating a "
                    "count, or a test checks each quoted figure"),
        falsifying_input="change a count in the code and confirm a prose check fails",
        source="doc-reviewer",
    ),
    Task(
        id="TASK-042", type="story", epic="DOCUMENTATION", priority="P2",
        status="TODO", owner="viewer", evidence="the browser",
        title="CALCULATOR: exam permission is not a training affordance",
        why=("SectionSpec.calculator records what the exam allows. Whether the APP "
             "should offer one is a separate decision, and the default must not let a "
             "calculator hide arithmetic weakness. Sits in tension with G9's own "
             "rationale."),
        acceptance=("a stated product decision, or the field split into "
                    "`exam_allows` and `training_offers`"),
        falsifying_input="n/a -- an open decision, not a code defect",
        source="Claude.ai + Perplexity.ai",
    ),
)


def by_epic() -> dict[str, list[Task]]:
    out: dict[str, list[Task]] = {}
    for t in TASKS:
        out.setdefault(t.epic, []).append(t)
    return out


def open_tasks() -> list[Task]:
    """Not DONE and not REJECTED, worst first."""
    order = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
    return sorted((t for t in TASKS if t.status in ("TODO", "BLOCKED")),
                  key=lambda t: (order[t.priority], t.id))


def render_csv() -> str:
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=COLUMNS, lineterminator="\n",
                       quoting=csv.QUOTE_ALL)
    w.writeheader()
    for t in TASKS:
        w.writerow(t.row())
    return buf.getvalue()


def render_board() -> str:
    """The human view: counts first, then the open work in priority order."""
    done = sum(1 for t in TASKS if t.status == "DONE")
    rej = sum(1 for t in TASKS if t.status == "REJECTED")
    lines = [
        f"TASK BOARD -- {len(TASKS)} records: {done} DONE, {rej} REJECTED, "
        f"{len(TASKS) - done - rej} open. Generated {RECORDED}.",
        "",
        "priority: " + " | ".join(f"{k} {v}" for k, v in PRIORITY_LEGEND.items()),
        "status:   " + " | ".join(f"{k} {v}" for k, v in STATUS_LEGEND.items()),
        "",
        "OPEN, worst first:",
    ]
    order = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
    for t in sorted(open_tasks(), key=lambda t: (order[t.priority], t.id)):
        blocker = (f"  (blocked by {t.blocked_by})" if t.blocked_by else "")
        lines.append(f"  {t.priority} {t.id}  [{t.epic}]  {t.owner:<15} {t.title}"
                     f"{blocker}")
    lines += ["", "CLOSED:", ]
    for t in TASKS:
        if t.status in ("DONE", "REJECTED"):
            lines.append(f"     {t.id}  {t.status:<8} {t.title}")
    return "\n".join(lines) + "\n"


__all__ = [
    "COLUMNS",
    "RECORDED",
    "TASKS",
    "Task",
    "by_epic",
    "date",
    "open_tasks",
    "render_board",
    "render_csv",
]
